### ISSUE TITLE
Have you tried it with MSSQL?

### ISSUE THREAD

**Issue by thedangler** [octoproject/octo-cli#1]
Wondering if you tried it with MSSQL?
We are in the process of turning our huge mssql server tables to be accessed through REST.

**Comment by amalkh5** [comment]
@thedangler yes we did, Octo support both MSSQL and Postgres.

**Comment by gregwebs** [comment]
How about MySQL? Is there a list of supported databases?

**Comment by amalkh5** [comment]
MySQL is not supported yet but it will be added later.

I will add soon a list of the supported databases.

**Comment by amalkh5** [comment]
@gregwebs I added the list of supported databases [here](https://github.com/octoproject/octo-cli#supported-databases)
