### ISSUE TITLE
Database support not specified

### ISSUE THREAD

**Issue by globalcitizen** [octoproject/octo-cli#4]
Readme should state clearly what format of databases are supported.

In one location you state "any database", others imply Postgres only.

Issue #1 is an example of confusion from this situation.

I personally came to see if you had sqlite support.

**Comment by amalkh5** [comment]
@globalcitizen I added the list to [readme](https://github.com/octoproject/octo-cli#supported-databases). `any database` implies that any database can be supported.

**Comment by globalcitizen** [comment]
Great. However, SQLite is not mentioned. Does this mean it is not supported?

**Comment by amalkh5** [comment]
@globalcitizen yes
